version: '3.8'

services:
  backend:
    image: ghcr.io/lyangend/sync/backend:master
    container_name: sync_backend
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    networks:
      - sync_network

  frontend:
    image: ghcr.io/lyangend/sync/frontend:master
    container_name: sync_frontend
    restart: always
    ports:
      - "3003:80"
    depends_on:
      - backend
    networks:
      - sync_network

networks:
  sync_network:
    driver: bridge